ALTER TABLE "estimates" ADD COLUMN "bodyRate" DOUBLE PRECISION NOT NULL DEFAULT 65;
ALTER TABLE "estimates" ADD COLUMN "paintRate" DOUBLE PRECISION NOT NULL DEFAULT 65;
ALTER TABLE "estimates" ADD COLUMN "supplyRate" DOUBLE PRECISION NOT NULL DEFAULT 38;
ALTER TABLE "estimates" ADD COLUMN "mechanicRate" DOUBLE PRECISION NOT NULL DEFAULT 54;
ALTER TABLE "estimate_line_items" ADD COLUMN "mechanicHours" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "estimates" ALTER COLUMN "bodyRate" SET DEFAULT 58;
ALTER TABLE "estimates" ALTER COLUMN "paintRate" SET DEFAULT 58;
