export type CollisionPresetItem = {
  category: string;
  operation: string;
  description: string;
  partNumber?: string;
  quantity?: number;
  note?: string;
  laborHours?: number;
  mechanicHours?: number;
  paintHours?: number;
  unitPrice?: number;
  subItems?: CollisionPresetItem[];
};

export const COLLISION_LINE_ITEM_PRESETS: CollisionPresetItem[] = [
  // Front bumper
  { category: "Front Bumper & Grille", operation: "Rpr", description: "Front bumper cover - repair", laborHours: 1.5, paintHours: 2, subItems: [{ category: "Front Bumper & Grille", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Front Bumper & Grille", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 }] },
  {
    category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper cover - replace", laborHours: 1.2, paintHours: 2.5,
    subItems: [
      { category: "Front Bumper & Grille", operation: "", description: "Add for clear coat", paintHours: 1 },
      { category: "Front Bumper & Grille", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 },
      { category: "Front Bumper & Grille", operation: "", description: "Add for parking aid sensor transfer", laborHours: 0.3 },
    ],
  },
  { category: "Front Bumper & Grille", operation: "R&I", description: "Front bumper cover - remove/install" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper absorber - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper reinforcement - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front grille - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front license plate bracket - replace" },
  // Rear bumper
  { category: "Rear Bumper", operation: "Rpr", description: "Rear bumper cover - repair", laborHours: 1.5, paintHours: 2 },
  {
    category: "Rear Bumper", operation: "Repl", description: "Rear bumper cover - replace", laborHours: 1.2, paintHours: 2.5,
    subItems: [
      { category: "Rear Bumper", operation: "", description: "Add for clear coat", paintHours: 1 },
      { category: "Rear Bumper", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 },
      { category: "Rear Bumper", operation: "", description: "Add for park assist / blind spot sensor", mechanicHours: 0.3 },
    ],
  },
  { category: "Rear Bumper", operation: "R&I", description: "Rear bumper cover - remove/install" },
  { category: "Rear Bumper", operation: "Repl", description: "Rear bumper absorber - replace" },
  { category: "Rear Bumper", operation: "Repl", description: "Rear bumper reinforcement - replace" },
  // Hood
  { category: "Hood", operation: "Rpr", description: "Hood - repair", laborHours: 2, paintHours: 2.5, subItems: [{ category: "Hood", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Hood", operation: "Repl", description: "Hood - replace", laborHours: 1.5, paintHours: 3, subItems: [{ category: "Hood", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Hood", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 }] },
  { category: "Hood", operation: "R&I", description: "Hood - remove/install" },
  { category: "Hood", operation: "Repl", description: "Hood hinge - replace" },
  { category: "Hood", operation: "Repl", description: "Hood latch - replace" },
  // Fenders
  { category: "Fenders", operation: "Rpr", description: "Front fender (left) - repair", laborHours: 1.8, paintHours: 2, subItems: [{ category: "Fenders", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Fenders", operation: "Rpr", description: "Front fender (right) - repair", laborHours: 1.8, paintHours: 2, subItems: [{ category: "Fenders", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Fenders", operation: "Repl", description: "Front fender (left) - replace", laborHours: 1.3, paintHours: 2.5, subItems: [{ category: "Fenders", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Fenders", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 }] },
  { category: "Fenders", operation: "Repl", description: "Front fender (right) - replace", laborHours: 1.3, paintHours: 2.5, subItems: [{ category: "Fenders", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Fenders", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 }] },
  { category: "Fenders", operation: "Repl", description: "Fender liner (left) - replace" },
  { category: "Fenders", operation: "Repl", description: "Fender liner (right) - replace" },
  // Lighting
  { category: "Lighting", operation: "Repl", description: "Headlight assembly (left) - replace", subItems: [{ category: "Lighting", operation: "", description: "Aim headlamps", laborHours: 0.5 }] },
  { category: "Lighting", operation: "Repl", description: "Headlight assembly (right) - replace", subItems: [{ category: "Lighting", operation: "", description: "Aim headlamps", laborHours: 0.5 }] },
  { category: "Lighting", operation: "Repl", description: "Taillight assembly (left) - replace" },
  { category: "Lighting", operation: "Repl", description: "Taillight assembly (right) - replace" },
  { category: "Lighting", operation: "Repl", description: "Fog light (left) - replace" },
  { category: "Lighting", operation: "Repl", description: "Fog light (right) - replace" },
  // Doors
  { category: "Doors", operation: "Rpr", description: "Front door (left) - repair", laborHours: 2.5, paintHours: 2.5, subItems: [{ category: "Doors", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Doors", operation: "Rpr", description: "Front door (right) - repair", laborHours: 2.5, paintHours: 2.5, subItems: [{ category: "Doors", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Doors", operation: "Rpr", description: "Rear door (left) - repair", laborHours: 2.2, paintHours: 2.2 },
  { category: "Doors", operation: "Rpr", description: "Rear door (right) - repair", laborHours: 2.2, paintHours: 2.2 },
  { category: "Doors", operation: "Repl", description: "Front door shell (left) - replace", laborHours: 3, paintHours: 3, subItems: [{ category: "Doors", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Doors", operation: "", description: "Add for corrosion protection", laborHours: 0.3 }] },
  { category: "Doors", operation: "Repl", description: "Front door shell (right) - replace", laborHours: 3, paintHours: 3, subItems: [{ category: "Doors", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Doors", operation: "", description: "Add for corrosion protection", laborHours: 0.3 }] },
  { category: "Doors", operation: "Repl", description: "Rear door shell (left) - replace", laborHours: 3, paintHours: 3 },
  { category: "Doors", operation: "Repl", description: "Rear door shell (right) - replace", laborHours: 3, paintHours: 3 },
  { category: "Doors", operation: "R&I", description: "Front door - remove/install" },
  { category: "Doors", operation: "R&I", description: "Rear door - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door trim panel - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door belt molding - remove/install" },
  { category: "Doors", operation: "Repl", description: "Door hinge (left) - replace", laborHours: 0.8 },
  { category: "Doors", operation: "Repl", description: "Door hinge (right) - replace", laborHours: 0.8 },
  { category: "Doors", operation: "Repl", description: "Door latch/lock assembly - replace", laborHours: 0.8 },
  { category: "Doors", operation: "Blnd", description: "Door blend panel", paintHours: 1 },
  { category: "Doors", operation: "Repl", description: "Door handle (exterior) - replace" },
  { category: "Doors", operation: "Repl", description: "Door mirror (left) - replace" },
  { category: "Doors", operation: "Repl", description: "Door mirror (right) - replace" },
  { category: "Doors", operation: "Repl", description: "Door glass - replace" },
  { category: "Doors", operation: "Repl", description: "Door weatherstrip - replace" },
  { category: "Doors", operation: "Repl", description: "Door glass regulator - replace", mechanicHours: 1 },
  { category: "Doors", operation: "R&I", description: "Door glass - remove/install" },
  // Quarter panels / rear
  { category: "Quarter Panels", operation: "Rpr", description: "Quarter panel (left) - repair", laborHours: 3, paintHours: 3, subItems: [{ category: "Quarter Panels", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Quarter Panels", operation: "Rpr", description: "Quarter panel (right) - repair", laborHours: 3, paintHours: 3, subItems: [{ category: "Quarter Panels", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Quarter Panels", operation: "Repl", description: "Quarter panel (left) - replace", laborHours: 6, paintHours: 3.5, subItems: [{ category: "Quarter Panels", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Quarter Panels", operation: "", description: "Add for corrosion protection", laborHours: 0.3 }] },
  { category: "Quarter Panels", operation: "Repl", description: "Quarter panel (right) - replace", laborHours: 6, paintHours: 3.5, subItems: [{ category: "Quarter Panels", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Quarter Panels", operation: "", description: "Add for corrosion protection", laborHours: 0.3 }] },
  { category: "Quarter Panels", operation: "Blnd", description: "Quarter panel blend", paintHours: 1.2 },
  // Trunk / hatch / roof
  { category: "Trunk & Roof", operation: "Rpr", description: "Trunk lid - repair", laborHours: 1.8, paintHours: 2.2, subItems: [{ category: "Trunk & Roof", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Trunk & Roof", operation: "Repl", description: "Trunk lid - replace", laborHours: 1.4, paintHours: 2.6, subItems: [{ category: "Trunk & Roof", operation: "", description: "Add for clear coat", paintHours: 1 }] },
  { category: "Trunk & Roof", operation: "Repl", description: "Liftgate/hatch - replace", laborHours: 1.6, paintHours: 2.6, subItems: [{ category: "Trunk & Roof", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Trunk & Roof", operation: "", description: "Add for corrosion protection", laborHours: 0.3 }] },
  { category: "Trunk & Roof", operation: "Rpr", description: "Roof panel - repair", laborHours: 3.5, paintHours: 3.5 },
  { category: "Trunk & Roof", operation: "Repl", description: "Rear spoiler - replace" },
  // Glass
  { category: "Glass", operation: "Repl", description: "Windshield - replace", laborHours: 1.5, subItems: [{ category: "Glass", operation: "", description: "Add for molding / clip installation", laborHours: 0.2 }] },
  { category: "Glass", operation: "Repl", description: "Rear window - replace", laborHours: 1.2 },
  { category: "Glass", operation: "Repl", description: "Side mirror glass - replace" },
  // Frame / structural
  { category: "Frame & Structural", operation: "Rpr", description: "Frame rail (left) - straighten", laborHours: 4 },
  { category: "Frame & Structural", operation: "Rpr", description: "Frame rail (right) - straighten", laborHours: 4 },
  { category: "Frame & Structural", operation: "Rpr", description: "Radiator support - repair", laborHours: 2 },
  { category: "Frame & Structural", operation: "Repl", description: "Radiator support - replace", laborHours: 2.5 },
  { category: "Frame & Structural", operation: "Diag", description: "Frame measuring / diagnostic scan", laborHours: 1 },
  // Mechanical / cooling / suspension
  { category: "Mechanical", operation: "Repl", description: "Radiator - replace", laborHours: 1.5 },
  { category: "Mechanical", operation: "Repl", description: "AC condenser - replace", laborHours: 1.5 },
  { category: "Mechanical", operation: "Repl", description: "Suspension strut (left) - replace", laborHours: 1.2 },
  { category: "Mechanical", operation: "Repl", description: "Suspension strut (right) - replace", laborHours: 1.2 },
  { category: "Mechanical", operation: "Repl", description: "Control arm - replace", laborHours: 1.4 },
  { category: "Mechanical", operation: "Align", description: "Wheel alignment", laborHours: 1 },
  { category: "Mechanical", operation: "Repl", description: "Wheel/rim - replace" },
  { category: "Mechanical", operation: "Repl", description: "Tire - replace" },
  // Airbags / safety
  { category: "Safety Systems", operation: "Repl", description: "Airbag module - replace", laborHours: 1.5 },
  { category: "Safety Systems", operation: "Repl", description: "Seat belt pretensioner - replace", laborHours: 1 },
  { category: "Safety Systems", operation: "Calib", description: "ADAS camera calibration", laborHours: 1.5 },
  { category: "Safety Systems", operation: "Calib", description: "Radar sensor calibration", laborHours: 1.5 },
  { category: "Safety Systems", operation: "Diag", description: "Pre-repair diagnostic scan", laborHours: 0.5 },
  { category: "Safety Systems", operation: "Diag", description: "Post-repair diagnostic scan", laborHours: 0.5 },
  // Paint & refinish
  { category: "Paint & Refinish", operation: "Refn", description: "Overall vehicle refinish" },
  { category: "Paint & Refinish", operation: "Refn", description: "Panel refinish - single panel", paintHours: 2, subItems: [{ category: "Paint & Refinish", operation: "", description: "Add for clear coat", paintHours: 1 }, { category: "Paint & Refinish", operation: "", description: "Add for tri-coat paint", paintHours: 0.8 }] },
  { category: "Paint & Refinish", operation: "Blnd", description: "Adjacent panel blend", paintHours: 1 },
  { category: "Paint & Refinish", operation: "Clear", description: "Clear coat application", paintHours: 1 },
  // Shop / misc
  { category: "Shop & Misc", operation: "Misc", description: "Hazardous waste disposal fee" },
  { category: "Shop & Misc", operation: "Misc", description: "Shop supplies" },
  { category: "Shop & Misc", operation: "Misc", description: "Vehicle wash / detail" },
  { category: "Shop & Misc", operation: "Misc", description: "Rental car reimbursement" },
  { category: "Shop & Misc", operation: "Misc", description: "Towing fee" },
  { category: "Shop & Misc", operation: "Diag", description: "Pre-repair diagnostic scan" },
  { category: "Shop & Misc", operation: "Diag", description: "Post-repair diagnostic scan" },
  { category: "Shop & Misc", operation: "Misc", description: "Corrosion protection materials" },
  { category: "Shop & Misc", operation: "Misc", description: "Seam sealer / cavity wax" },
  { category: "Shop & Misc", operation: "Misc", description: "Masking and paint protection" },
  { category: "Shop & Misc", operation: "Misc", description: "Fasteners and clips" },
  { category: "Shop & Misc", operation: "Rpr", description: "Water leak / air leak check", laborHours: 0.5 },
  // Items transcribed from the Mastercraft 2023 Chevrolet Suburban estimate.
  { category: "Front Bumper & Grille", operation: "O/H", description: "Bumper assembly - overhaul", laborHours: 3.8 },
  {
    category: "Front Bumper & Grille", operation: "Repl", description: "Non-OEM CAPA bumper cover with parking aid, without hands-free liftgate", partNumber: "GM1000A46C", unitPrice: 309.23, paintHours: 3.3,
    subItems: [
      { category: "Front Bumper & Grille", operation: "", description: "Add for clear coat", paintHours: 1.3 },
      { category: "Front Bumper & Grille", operation: "", description: "Add for parking sensor", laborHours: 0.4 },
    ],
  },
  { category: "Lighting", operation: "Repl", description: "Left headlamp assembly - remanufactured", partNumber: "86538943", unitPrice: 952.75, laborHours: 0.5 },
  {
    category: "Fenders", operation: "Rpr", description: "Left fender - repair", partNumber: "84384210", laborHours: 2, paintHours: 2.2,
    subItems: [
      { category: "Fenders", operation: "", description: "Overlap major non-adjacent panel", laborHours: -0.2 },
      { category: "Fenders", operation: "", description: "Add for clear coat", paintHours: 0.4 },
      { category: "Fenders", operation: "", description: "Feather, prime and block", laborHours: 0.5 },
      { category: "Fenders", operation: "", description: "Basecoat reduction", paintHours: -0.2 },
    ],
  },
  { category: "Fenders", operation: "R&I", description: "Left fender liner - remove/install, without Z71", partNumber: "84856823", laborHours: 0.3 },
  { category: "Wheels", operation: "R&I", description: "Left front wheel - remove/install", partNumber: "23376234", laborHours: 0.1 },
  { category: "Wheels", operation: "Subl", description: "Left front 22-inch alloy wheel", partNumber: "23376234", unitPrice: 149.99, note: "Code SGF; taxable" },
  { category: "Pillars, Rocker & Floor", operation: "R&I", description: "Left black step bar assembly - remove/install", partNumber: "84809514", laborHours: 0.7 },
  {
    category: "Doors", operation: "Rpr", description: "Left door shell - repair, without body side moldings (aluminum)", partNumber: "85841901", laborHours: 2, paintHours: 2.4,
    subItems: [
      { category: "Doors", operation: "", description: "Overlap major adjacent panel", laborHours: -0.4 },
      { category: "Doors", operation: "", description: "Add for clear coat", paintHours: 0.4 },
      { category: "Doors", operation: "", description: "Feather, prime and block", laborHours: 0.5 },
      { category: "Doors", operation: "", description: "Basecoat reduction", paintHours: -0.2 },
    ],
  },
  { category: "Doors", operation: "Repl", description: "Left black belt molding - replace", partNumber: "84844389", unitPrice: 83.15, laborHours: 0.3 },
  { category: "Doors", operation: "Repl", description: "Black SUBURBAN nameplate - replace", partNumber: "84470959-AT", unitPrice: 14, laborHours: 0.2 },
  { category: "Doors", operation: "Repl", description: "Recycled left mirror assembly with surround view +25%", partNumber: "JKH055", unitPrice: 231.25, laborHours: 0.6 },
  { category: "Doors", operation: "R&I", description: "Left outside door handle - remove/install, without chrome", partNumber: "13526766", laborHours: 0.4 },
  { category: "Doors", operation: "R&I", description: "Left door trim panel - remove/install", partNumber: "85651067", laborHours: 0.4 },
  { category: "Shop & Misc", operation: "Repl", description: "Additional cover car/mask for primer", quantity: 1, unitPrice: 5, laborHours: 0.2 },
  { category: "Shop & Misc", operation: "Repl", description: "Corrosion protection", quantity: 1, laborHours: 0.3 },
  { category: "Shop & Misc", operation: "Repl", description: "Flex additive", quantity: 1, unitPrice: 12 },
  { category: "Safety Systems", operation: "Rpr", description: "Post-repair scan", mechanicHours: 0.5 },
  { category: "Safety Systems", operation: "Rpr", description: "Pre-repair scan", mechanicHours: 0.5 },
  { category: "Mechanical", operation: "Subl", description: "Front end alignment", quantity: 1, unitPrice: 99.99 },
  { category: "Mechanical", operation: "Subl", description: "Mount and balance", quantity: 1, unitPrice: 25 },
  { category: "Safety Systems", operation: "R&I", description: "Disconnect/reconnect battery and disable airbag system", laborHours: 0.2 },
  { category: "Shop & Misc", operation: "Misc", description: "E.P.C.", quantity: 1, unitPrice: 2 },
  // Additional checklist items; leave labor times blank until verified for the vehicle and procedure.
  { category: "Front Bumper & Grille", operation: "R&I", description: "Front bumper grille - remove/install" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper grille insert - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper side retainer (left) - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper side retainer (right) - replace" },
  { category: "Front Bumper & Grille", operation: "R&I", description: "Front bumper impact absorber - remove/install" },
  { category: "Front Bumper & Grille", operation: "R&I", description: "Front bumper reinforcement - remove/install" },
  { category: "Front Bumper & Grille", operation: "R&I", description: "Front bumper cover - transfer attached components" },
  { category: "Front Bumper & Grille", operation: "Diag", description: "Inspect bumper-mounted sensors and brackets", subItems: [{ category: "Front Bumper & Grille", operation: "", description: "Document sensor/bracket condition" }] },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front bumper tow hook cover - replace" },
  { category: "Front Bumper & Grille", operation: "Repl", description: "Front lower air deflector - replace" },
  { category: "Rear Bumper", operation: "R&I", description: "Rear bumper grille / valance - remove/install" },
  { category: "Rear Bumper", operation: "Repl", description: "Rear bumper side retainer (left) - replace" },
  { category: "Rear Bumper", operation: "Repl", description: "Rear bumper side retainer (right) - replace" },
  { category: "Rear Bumper", operation: "R&I", description: "Rear bumper reinforcement - remove/install" },
  { category: "Rear Bumper", operation: "R&I", description: "Rear bumper cover - transfer attached components" },
  { category: "Rear Bumper", operation: "R&I", description: "Trailer hitch / bumper access trim - remove/install" },
  { category: "Rear Bumper", operation: "Repl", description: "Rear bumper tow hook cover - replace" },
  { category: "Rear Bumper", operation: "Diag", description: "Inspect rear parking / blind-spot sensors and brackets", subItems: [{ category: "Rear Bumper", operation: "", description: "Document sensor/bracket condition" }] },
  { category: "Hood", operation: "R&I", description: "Hood insulation pad - remove/install" },
  { category: "Hood", operation: "R&I", description: "Hood latch / release cable - remove/install" },
  { category: "Hood", operation: "Repl", description: "Hood release cable - replace" },
  { category: "Hood", operation: "R&I", description: "Hood panel - align / adjust", subItems: [{ category: "Hood", operation: "", description: "Check latch engagement and panel gaps" }] },
  { category: "Fenders", operation: "R&I", description: "Front fender - remove/install" },
  { category: "Fenders", operation: "R&I", description: "Fender liner / splash shield - remove/install" },
  { category: "Fenders", operation: "R&I", description: "Fender flare / molding - remove/install" },
  { category: "Fenders", operation: "Repl", description: "Fender flare / molding - replace" },
  { category: "Fenders", operation: "Repl", description: "Fender apron extension - replace" },
  { category: "Fenders", operation: "Blnd", description: "Blend adjacent front door" },
  { category: "Lighting", operation: "R&I", description: "Headlight assembly (left) - remove/install" },
  { category: "Lighting", operation: "R&I", description: "Headlight assembly (right) - remove/install" },
  { category: "Lighting", operation: "R&I", description: "Taillight assembly (left) - remove/install" },
  { category: "Lighting", operation: "R&I", description: "Taillight assembly (right) - remove/install" },
  { category: "Lighting", operation: "Repl", description: "Daytime running lamp - replace" },
  { category: "Lighting", operation: "Repl", description: "Center high-mounted stop lamp - replace" },
  { category: "Lighting", operation: "Diag", description: "Check exterior lamp operation after repair" },
  { category: "Doors", operation: "R&I", description: "Front door shell - remove/install" },
  { category: "Doors", operation: "R&I", description: "Rear door shell - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door handle (exterior) - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door mirror assembly - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door intrusion beam - remove/install" },
  { category: "Doors", operation: "Repl", description: "Window run channel - replace" },
  { category: "Doors", operation: "Repl", description: "Door belt molding (left) - replace" },
  { category: "Doors", operation: "Repl", description: "Door belt molding (right) - replace" },
  { category: "Doors", operation: "R&I", description: "Door water deflector - remove/install" },
  { category: "Doors", operation: "R&I", description: "Door harness / electrical connector - remove/install" },
  { category: "Doors", operation: "Diag", description: "Check window, lock, mirror and entry functions", subItems: [{ category: "Doors", operation: "", description: "Check warning lamps / door ajar operation" }] },
  { category: "Doors", operation: "Blnd", description: "Blend adjacent rear door / quarter panel" },
  { category: "Quarter Panels", operation: "R&I", description: "Quarter glass - remove/install" },
  { category: "Quarter Panels", operation: "R&I", description: "Wheelhouse liner - remove/install" },
  { category: "Quarter Panels", operation: "R&I", description: "Quarter panel trim / applique - remove/install" },
  { category: "Quarter Panels", operation: "Repl", description: "Quarter panel extension - replace" },
  { category: "Quarter Panels", operation: "Rpr", description: "Wheelhouse outer - repair", subItems: [{ category: "Quarter Panels", operation: "", description: "Restore seam sealer as required" }, { category: "Quarter Panels", operation: "", description: "Apply corrosion protection per OEM procedure" }] },
  { category: "Quarter Panels", operation: "Blnd", description: "Blend adjacent rear door / deck panel" },
  { category: "Trunk & Roof", operation: "R&I", description: "Liftgate / hatch - remove/install" },
  { category: "Trunk & Roof", operation: "R&I", description: "Trunk trim and finish panel - remove/install" },
  { category: "Trunk & Roof", operation: "Repl", description: "Trunk weatherstrip - replace" },
  { category: "Trunk & Roof", operation: "Repl", description: "Deck lid hinge (left) - replace" },
  { category: "Trunk & Roof", operation: "Repl", description: "Deck lid hinge (right) - replace" },
  { category: "Trunk & Roof", operation: "R&I", description: "Roof rack / molding - remove/install" },
  { category: "Trunk & Roof", operation: "Repl", description: "Roof molding / applique - replace" },
  { category: "Trunk & Roof", operation: "Blnd", description: "Blend adjacent quarter panel" },
  { category: "Glass", operation: "R&I", description: "Windshield - remove/install" },
  { category: "Glass", operation: "R&I", description: "Rear window - remove/install" },
  { category: "Glass", operation: "Repl", description: "Door glass (left) - replace" },
  { category: "Glass", operation: "Repl", description: "Door glass (right) - replace" },
  { category: "Glass", operation: "Repl", description: "Quarter glass (left) - replace" },
  { category: "Glass", operation: "Repl", description: "Quarter glass (right) - replace" },
  { category: "Glass", operation: "Repl", description: "Backlite molding / reveal molding - replace" },
  { category: "Glass", operation: "Diag", description: "Water leak test after glass installation" },
  { category: "Glass", operation: "Calib", description: "ADAS camera calibration after glass service", subItems: [{ category: "Glass", operation: "", description: "Pre-scan / post-scan as required by OEM procedure" }] },
  { category: "Frame & Structural", operation: "Diag", description: "Document pre-repair structural measurements" },
  { category: "Frame & Structural", operation: "Diag", description: "Document post-repair structural measurements" },
  { category: "Frame & Structural", operation: "R&I", description: "Set up / anchor vehicle on frame equipment" },
  { category: "Frame & Structural", operation: "Rpr", description: "Structural pull / correction - document procedure", subItems: [{ category: "Frame & Structural", operation: "", description: "Weld test / destructive test if required by OEM" }, { category: "Frame & Structural", operation: "", description: "Restore seam sealer and corrosion protection per OEM procedure" }] },
  { category: "Frame & Structural", operation: "Repl", description: "Uniside / structural section - replace per OEM procedure" },
  { category: "Frame & Structural", operation: "Repl", description: "Floor pan section - replace per OEM procedure" },
  { category: "Frame & Structural", operation: "Repl", description: "Rear body panel - replace" },
  { category: "Mechanical", operation: "R&I", description: "Cooling system - drain / refill and bleed" },
  { category: "Mechanical", operation: "R&I", description: "Air conditioning system - recover / recharge if disturbed" },
  { category: "Mechanical", operation: "Repl", description: "Suspension knuckle (left) - replace" },
  { category: "Mechanical", operation: "Repl", description: "Suspension knuckle (right) - replace" },
  { category: "Mechanical", operation: "Align", description: "Four-wheel alignment check / adjustment" },
  { category: "Mechanical", operation: "Diag", description: "Mechanical post-repair inspection" },
  { category: "Mechanical", operation: "Repl", description: "Exhaust component - replace if damaged" },
  { category: "Safety Systems", operation: "Diag", description: "Pre-repair scan - attach scan report" },
  { category: "Safety Systems", operation: "Diag", description: "Post-repair scan - attach scan report" },
  { category: "Safety Systems", operation: "Calib", description: "ADAS calibration - procedure per OEM", subItems: [{ category: "Safety Systems", operation: "", description: "Static calibration if specified" }, { category: "Safety Systems", operation: "", description: "Dynamic calibration / road test if specified" }] },
  { category: "Safety Systems", operation: "Calib", description: "Blind-spot / parking sensor calibration per OEM" },
  { category: "Safety Systems", operation: "Diag", description: "Restraint system inspection / verification" },
  { category: "Safety Systems", operation: "Repl", description: "Airbag deployment component - replace per OEM procedure" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish bumper cover" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish hood" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish front fender (left)" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish front fender (right)" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish front door" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish rear door" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish quarter panel" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish roof panel" },
  { category: "Paint & Refinish", operation: "Refn", description: "Refinish deck lid / liftgate" },
  { category: "Paint & Refinish", operation: "Blnd", description: "Blend adjacent panel - left side" },
  { category: "Paint & Refinish", operation: "Blnd", description: "Blend adjacent panel - right side" },
  { category: "Paint & Refinish", operation: "Misc", description: "Mask / protect adjacent panels and vehicle interior" },
  { category: "Paint & Refinish", operation: "Misc", description: "Color match / spray-out card" },
  { category: "Paint & Refinish", operation: "Misc", description: "Denib / polish refinish surface" },
  { category: "Shop & Misc", operation: "Diag", description: "Vehicle pre-repair condition photos" },
  { category: "Shop & Misc", operation: "Diag", description: "Vehicle post-repair quality inspection" },
  { category: "Shop & Misc", operation: "Misc", description: "Hazardous-material handling / disposal (document quantity)" },
  { category: "Shop & Misc", operation: "Misc", description: "Sublet operation - attach vendor invoice" },
  { category: "Shop & Misc", operation: "Misc", description: "Storage / lot fee (document dates)" },
  { category: "Shop & Misc", operation: "Misc", description: "Supplemental damage documentation" },
];

export const COLLISION_LINE_ITEM_CATEGORIES = Array.from(
  new Set(COLLISION_LINE_ITEM_PRESETS.map((item) => item.category)),
);
